Repository JumpMind/openpos-framework, pull requests merged in 2020-10, with the labels that each got.

#898 Fix endpoint override implementation search algorithm
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointDispatchInvocationHandler.java
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointOverride.java
Labels: releasenote

#897 Add ability to override states
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/StateOverride.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/config/YamlConfigConverter.java
  openpos-flow/src/test/java/org/jumpmind/pos/core/flow/config/YamlConfigProviderTest.java
  openpos-flow/src/test/java/org/jumpmind/pos/core/flow/config/YamlTestStates.java
  openpos-flow/src/test/resources/testflows/test-flow.yml
Labels: releasenote

#910 Configure single endpoint
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointDispatchInvocationHandler.java
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/IInvocationStrategy.java
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/LocalOnlyStrategy.java
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/RemoteFirstStrategy.java
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/RemoteOnlyStrategy.java
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/SimulatedRemoteStrategy.java
  openpos-service/src/test/java/org/jumpmind/pos/service/RemoteOnlyStrategyTest.java
Labels: bug, releasenote

#915 Provide a dynamic mechanism to configure whether test failures should be ignored
  openpos-gradle/src/main/resources/java.gradle
Labels: enhancement, releasenote

#920 Versions not showing up when deployed as spring boot app
  openpos-util/src/main/java/org/jumpmind/pos/util/Versions.java
Labels: bug, releasenote

#930 Updated UI to support all transaction types
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/icon.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/transaction.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/_transaction-search-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/_transaction-summary-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/transaction-history-part/transaction-history-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/transaction-status.enum.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/_app-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/public-api.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/IconType.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/TransactionSummary.java
Labels: majorfeature, releasenote

#931 Feature/trans search results facelift master
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/icon.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/transaction.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/_transaction-search-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/_transaction-summary-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/transaction-history-part/transaction-history-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/transaction-status.enum.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/_app-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/public-api.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/IconType.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/TransactionSummary.java
Labels: majorfeature, releasenote
