Repository JumpMind/openpos-framework, pull requests merged in 2020-11, with the labels that each got.

#941 Cancel all executors after the state manager has been reset
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/ApplicationState.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/AsyncExecutor.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/StateManager.java
  openpos-flow/src/test/java/org/jumpmind/pos/core/flow/AsyncExecutorTest.java
Labels: enhancement, releasenote

#943 Rounding isn't precise enough to avoid penny errors
  openpos-util/src/main/groovy/org/jumpmind/pos/util/ProrationCalculator.groovy
  openpos-util/src/test/groovy/org/jumpmind/pos/util/ProrationCalculatorTest.groovy
Labels: bug, releasenote

#945 Added electronic journal to the transaction search
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/icon.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/transaction.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/pos-screen/pos-screen.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/_transaction-search-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search-mode.enum.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/primary-button/primary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/secondary-button/secondary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/trans-status.enum.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/trans-type.enum.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/public-api.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/model/Form.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/IconType.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/TransactionSummary.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/TransactionSearchMode.java
  openpos-flow/src/main/resources/content/icons/notebook.svg
  openpos-flow/src/main/resources/content/icons/wb_incandescent_up.svg
  openpos-service/src/main/java/org/jumpmind/pos/service/util/DateUtils.java
  openpos-util/src/main/java/org/jumpmind/pos/util/model/Message.java
Labels: majorfeature, parameterchange, releasenote

#944 Added electronic journal to the transaction search
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/icon.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/transaction.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/pos-screen/pos-screen.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/_transaction-search-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search-mode.enum.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/primary-button/primary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/secondary-button/secondary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/trans-status.enum.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/trans-type.enum.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/public-api.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/model/Form.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/IconType.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/UIMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/TransactionSummary.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/TransactionSearchMode.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/TransactionSearchUIMessage.java
  openpos-flow/src/main/resources/content/icons/notebook.svg
  openpos-flow/src/main/resources/content/icons/wb_incandescent_up.svg
  openpos-service/src/main/java/org/jumpmind/pos/service/util/DateUtils.java
  openpos-util/src/main/java/org/jumpmind/pos/util/model/Message.java
Labels: majorfeature, parameterchange, releasenote

#952 sslEnabled=false as a query param turns ssl on
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/personalization-startup-task.ts
Labels: bug, releasenote

#948 Bugfix/keypress sources capturing both keyup and keydown
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/lock-screen/lock-screen.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/lock-screen/lock-screen.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/action-item-key-mapping.directive.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/keypress-source.directive.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/providers/keypress.provider.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part/prompt-form-part.component.ts
Labels: releasenote

#949 Bugfix/keypress sources capturing both keyup and keydown master
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/lock-screen/lock-screen.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/lock-screen/lock-screen.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/action-item-key-mapping.directive.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/keypress-source.directive.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/providers/keypress.provider.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part/prompt-form-part.component.ts
Labels: releasenote

#960 Auto-focus on first options element
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/options-list/options-list.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/options-list/options-list.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/options-list/options-list.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/messagepart/OptionsListPart.java
Labels: releasenote

#961 Fixed keybinding not working after lock screen closed
  openpos-client-libs/package-lock.json
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/lock-screen/lock-screen.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/stay-focused.directive.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/providers/keypress.provider.ts
Labels: releasenote

#962 Fixed keybinding not working after lock screen closed
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/lock-screen/lock-screen.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/stay-focused.directive.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/providers/keypress.provider.ts
Labels: releasenote

#970 Fixed keybindings not working after lock screen closed by always list…
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/stay-focused.directive.ts
Labels: releasenote

#969 Fixed keybinding not working after lock screen closed (timing fix)
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/stay-focused.directive.ts
Labels: releasenote

#972 Provider access to appId in ITagProvider
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/PersonalizeEndpoint.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/ITagProvider.java
Labels: apichange, releasenote

#974 Add muted-color class to menu disabled items
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/bacon-strip/bacon-drawer/bacon-drawer.component.html
Labels: enhancement, releasenote

#979 Add filters to transaction search screen.
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/_transaction-search-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/TransactionSummaryFilter.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/TransactionSearchUIMessage.java
Labels: releasenote

#978 Order devices in the personalization drop down alphabetically
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.component.ts
Labels: releasenote

#980 Allow calls to systems with self signed certs
  openpos-util/build.gradle
  openpos-util/src/main/java/org/jumpmind/pos/util/web/ConfiguredRestTemplate.java
Labels: releasenote

#983 Mobile style updates - Round 1
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/dialog/generic-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/home/home.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/options/options-screen-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt-with-info/prompt-with-info-screen-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt/prompt-screen-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt/prompt-screen-dialog.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/option-button/option-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/primary-button/_primary-button-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/primary-button/primary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/secondary-button/_secondary-button-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/secondary-button/secondary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/bacon-strip/bacon-strip.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dialog-header/dialog-header.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dialog-header/dialog-header.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part/prompt-form-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part/prompt-form-part.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/scan-or-search/scan-or-search.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/scan-or-search/scan-or-search.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/_app-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/_core.scss
Labels: releasenote

#982 Mobile style updates - Round 1
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/dialog/generic-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/home/home.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/options/options-screen-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt-with-info/prompt-with-info-screen-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt/prompt-screen-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt/prompt-screen-dialog.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/option-button/option-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/primary-button/_primary-button-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/primary-button/primary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/secondary-button/_secondary-button-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/secondary-button/secondary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/bacon-strip/bacon-strip.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dialog-header/dialog-header.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dialog-header/dialog-header.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part/prompt-form-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part/prompt-form-part.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/scan-or-search/scan-or-search.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/scan-or-search/scan-or-search.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/_app-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/_core.scss
Labels: releasenote

#984 Add module loader config
  openpos-service/src/main/java/org/jumpmind/pos/service/AbstractRDBMSModule.java
  openpos-service/src/main/java/org/jumpmind/pos/service/ModuleLoaderConfig.java
  openpos-service/src/test/java/org/jumpmind/pos/service/AbstractRDBMSModuleTest.java
Labels: parameterchange, releasenote

#987 Mobile Dialog Style Fixes
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt/prompt-screen-dialog.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/content-card/_content-card-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/content-card/content-card.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/primary-button/primary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/secondary-button/secondary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dialog-header/dialog-header.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/variables/_spacing.scss
Labels: releasenote

#986 Mobile Dialog Style Fixes
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt/prompt-screen-dialog.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/content-card/_content-card-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/content-card/content-card.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/primary-button/primary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/secondary-button/secondary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dialog-header/dialog-header.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/variables/_spacing.scss
Labels: releasenote

#989 Fixed touch devices playing the mouse click sound
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/audio/audio-interaction.service.ts
Labels: releasenote

#988 Fixed touch devices playing the mouse click sound
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/audio/audio-interaction.service.ts
Labels: releasenote

#992 Add socket factory that can be used to trust self signed certs
  openpos-util/src/main/java/org/jumpmind/pos/util/security/SelfSignedX509TrustManager.java
  openpos-util/src/main/java/org/jumpmind/pos/util/security/TrustSSLSocketFactory.java
Labels: releasenote
