Repository JumpMind/openpos-framework, pull requests merged in 2020-12, with the labels that each got.

#1003 Bugfix/updates to item detail component
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/promotion.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/Promotion.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/ItemDetailUIMessage.java
Labels: releasenote

#1004 Bugfix/updates to item detail component master
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/promotion.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/Promotion.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/ItemDetailUIMessage.java
Labels: releasenote

#1006 Added dark-blue theme
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/interfaces/sell-item.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/currency-text/currency-text.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/currency-text/currency-text.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/item-card/item-card.component.html
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/DefaultItem.java
Labels: majorfeature, releasenote

#1005 Added dark-blue theme
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/interfaces/sell-item.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/currency-text/currency-text.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/currency-text/currency-text.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/item-card/item-card.component.html
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/DefaultItem.java
Labels: majorfeature, releasenote

#1010 Support deviceless applications on the openpos framework. A central office dashboard would be an example.
  openpos-devices/src/main/java/org/jumpmind/pos/devices/DeviceUpdater.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/VirtualDeviceFilter.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/model/VirtualDeviceRepository.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/AuthenticateVirtualDeviceEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/DisconnectVirtualDeviceEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetMyVirtualDeviceEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetVirtualDeviceEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetVirtualDevicePersonalizationConfigEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/PersonalizeVirtualDeviceEndpoint.java
  openpos-util/src/main/java/org/jumpmind/pos/util/RandomString.java
Labels: releasenote

#1020 Provide a way for openpos framework users to update the client context with scoped values
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/IClientContextUpdater.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/StateManagerContainer.java
Labels: releasenote

#1022 Support running under java 15
  openpos-assemble/build.gradle
  openpos-assemble/gradle/wrapper/gradle-wrapper.properties
  openpos-client-libs/build.gradle
  openpos-flow/src/main/java/org/jumpmind/pos/core/service/DefaultHttpConnectionService.java
  openpos-gradle/src/main/resources/release.gradle
  openpos-util/src/test/java/org/jumpmind/pos/util/BoolUtilsTest.java
Labels: releasenote

#1028 Fixed the linked loyalty button not showing on the returns screen
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/ReturnUIMessage.java
Labels: releasenote

#1027 Fixed the linked loyalty customer button not showing on the returns screen
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/ReturnUIMessage.java
Labels: releasenote

#1026 Add Prompt Buttons Support to Options Screen
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/options/options-screen-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/options/options-screen-dialog.component.scss
Labels: enhancement, releasenote

#1032 The percentint formatter is not working. It allows decimals
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/formatters/percentage.formatter.ts
Labels: bug, releasenote

#1030 Fixed sales total panel hiding loyalty button after capturing id
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.html
Labels: releasenote

#1031 Fixed sales total panel hiding loyalty button after capturing id
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.html
Labels: releasenote

#1040 Log calls to all endpoints with the exception of endpoints tagged to suppress logging
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/IDevicesService.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/model/SearchCriteria.java
  openpos-service/src/main/java/org/jumpmind/pos/service/AbstractServiceFactory.java
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
  openpos-service/src/test/java/org/jumpmind/pos/service/LocalOnlyStrategyTest.java
  openpos-util/src/main/java/org/jumpmind/pos/util/SuppressMethodLogging.java
Labels: releasenote

#1044 Support loading of files with the suffix of .batch as SymmetricDS batches. This will help with managing SymmetricDS configuration.
  openpos-persist/src/main/java/org/jumpmind/pos/persist/DatabaseScriptContainer.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/DatabaseSchema.java
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
Labels: enhancement, releasenote
