Repository JumpMind/openpos-framework, pull requests merged in 2021-08, with the labels that each got.

#1491 Feature/api tokens and rest path
  .gitignore
  openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DevicesRepository.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/AuthenticateDeviceEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetAllDevicesEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetDeviceEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetDevicePersonalizationModelEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetMyDeviceEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetPersonalizationConfigEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/IDevicesService.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/PersonalizeEndpoint.java
  openpos-server-core/src/main/java/org/jumpmind/pos/server/config/SwaggerConfig.java
  openpos-service/src/main/java/org/jumpmind/pos/service/ProfileConfig.java
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/RemoteOnlyStrategy.java
  openpos-service/src/test/java/org/jumpmind/pos/service/utils/AbstractServiceMockRequestBuilder.java
  openpos-util/src/main/java/org/jumpmind/pos/util/ApiTokenGenerator.java
  openpos-util/src/main/java/org/jumpmind/pos/util/RestApiSupport.java
  openpos-util/src/test/java/org/jumpmind/pos/util/ApiTokenGeneratorTest.java
Labels: apichange, enhancement

#1505 Dialog Header not Aligned with Content
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dialog-header/dialog-header.component.scss
Labels: bug

#1500 Fix showing build version
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.ts
Labels: bug

#1510 FIX CRITICAL BUG COSTING JUMPMIND MILLIONS
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dialog-header/dialog-header.component.scss
Labels: bug

#1526 Logging Inversion w/ New Relic sink support
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/commerce-server/commerce-server-sink.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/commerce-server/commerce-server-sink.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/commerce-server/log-method-type.enum.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/commerce-server/server-log-entry.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/commerce-server/server-logger-configuration.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/console-interceptor-bypass.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/console-interceptor-bypass.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/console-interceptor-config.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/console-interceptor.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/console-interceptor.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/console-scraper.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/logger.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/new-relic/new-relic-sink.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/new-relic/new-relic-sink.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/server-log-entry.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/server-logger-configuration.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/server-logger-it.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/server-logger.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/server-logger.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platforms/config-provider/capacitor/capacitor-platform-config.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platforms/config-provider/capacitor/capacitor-platform-config.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platforms/config-provider/capacitor/capacitor-plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platforms/config-provider/config-providers.module.ts
Labels: enhancement, releasenote

#1533 Add Some Membership Info to Loyalty Button
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/membership-display.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/membership-display.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/membership-display.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/memebership-display.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/CustomerDetailsUIMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/SaleUIMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UILoyaltyReward.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UIMembership.java
Labels: bug

#1534 Updates to enhance support for one server and multiple clients having different business unit IDs
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/auto-personalization-startup-task.ts
  openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DevicePersonalizationModel.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetDevicePersonalizationModelEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/PersonalizeEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/model/PersonalizeMeResponse.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/strategy/GetBusinessUnitIdFromConfigStrategy.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/strategy/GetBusinessUnitIdFromPersonalizationParamsStrategy.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/strategy/IDeviceBusinessUnitIdStrategy.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/strategy/ParseBusinessUnitIdFromDeviceIdStrategy.java
  openpos-devices/src/test/java/org/jumpmind/pos/devices/service/PersonalizationEndpointTest.java
  openpos-devices/src/test/java/org/jumpmind/pos/devices/service/strategy/GetBusinessUnitIdFromConfigStrategyTest.java
  openpos-devices/src/test/java/org/jumpmind/pos/devices/service/strategy/GetBusinessUnitIdFromPersonalizationParamsStrategyTest.java
  openpos-devices/src/test/java/org/jumpmind/pos/devices/service/strategy/ParseBusinessUnitIdFromDeviceIdStrategyTest.java
  openpos-devices/src/test/resources/application-test.yml
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/StateManager.java
  openpos-server-core/src/main/java/org/jumpmind/pos/server/service/SessionConnectListener.java
  openpos-service/src/main/java/org/jumpmind/pos/service/AbstractRDBMSModule.java
  openpos-util/src/main/java/org/jumpmind/pos/util/JSONUtils.java
  openpos-util/src/main/java/org/jumpmind/pos/util/clientcontext/ClientContext.java
Labels: releasenote, majorfeature, parameterchange, database change

#1539 Add Customer Form Extra Fields Not Aligned with Other Fields
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/loyalty-customer-form-dialog/loyalty-customer-form-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/loyalty-customer-form-dialog/loyalty-customer-form-dialog.component.scss
Labels: bug

#1544 Unit tests for Console Scraper
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/console-scraper.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/console-scrapper.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/new-relic/new-relic-sink.service.ts
Labels: bug

#1564 New Relic stopped sending logs
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/new-relic/new-relic-sink.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/new-relic/new-relic-sink.service.ts
Labels: bug
