Repository JumpMind/openpos-framework, pull requests merged in 2021-02, with the labels that each got.

#1102 Provide user prompts if a device is not registered or the initial load is in progress
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/StateManager.java
  openpos-symds/build.gradle
  openpos-symds/src/main/java/org/jumpmind/pos/symds/InitSymDSStep.java
  openpos-symds/src/main/java/org/jumpmind/pos/symds/SymDSModule.java
Labels: releasenote

#1094 Initial Release of Enhanced Training Mode Infrastructure
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/message-types.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/watermark-message.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-screen/dynamic-screen.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-screen/dynamic-screen.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-screen/dynamic-screen.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/watermark/watermark.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/watermark/watermark.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/watermark/watermark.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/shared.module.ts
  openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DeviceModel.java
  openpos-devices/src/test/java/org/jumpmind/pos/devices/DeviceTestUtils.java
  openpos-devices/src/test/java/org/jumpmind/pos/devices/model/DevicesRepositoryTest.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/ApplicationState.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/IClientContextUpdater.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/IStateManager.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/Scope.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/StateManager.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/StateManagerContainer.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/model/MessageType.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/HideWatermark.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/Watermark.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/Augmented.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSessionFactory.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/DatabaseSchema.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelClassMetaData.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelWrapper.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/QueryTemplate.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/QueryTemplates.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ShadowTablesConfigModel.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/model/AugmenterConfig.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/model/AugmenterConfigs.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/model/AugmenterHelper.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/model/AugmenterIndexConfig.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/model/AugmenterModel.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/model/IAugmentedModel.java
  openpos-persist/src/test/java/org/jumpmind/pos/persist/DBSessionQueryConcurrentTest.java
  openpos-persist/src/test/java/org/jumpmind/pos/persist/cars/DelegateTestContextConfig.java
  openpos-persist/src/test/java/org/jumpmind/pos/persist/cars/TestPersistCarsConfig.java
  openpos-persist/src/test/resources/persist-test-query.yml
  openpos-service/src/main/java/org/jumpmind/pos/service/AbstractRDBMSModule.java
  openpos-service/src/main/java/org/jumpmind/pos/service/AbstractServiceFactory.java
  openpos-service/src/main/java/org/jumpmind/pos/service/Endpoint.java
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointDispatchInvocationHandler.java
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointOverride.java
  openpos-service/src/main/java/org/jumpmind/pos/service/ModuleLoaderConfig.java
  openpos-service/src/main/java/org/jumpmind/pos/service/instrumentation/ServiceSampleModel.java
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/LocalOnlyStrategy.java
  openpos-service/src/main/java/org/jumpmind/pos/service/util/ClassUtils.java
  openpos-service/src/test/java/org/jumpmind/pos/service/LocalOnlyStrategyTest.java
  openpos-util/src/main/java/org/jumpmind/pos/util/SuppressMethodLogging.java
  openpos-util/src/main/java/org/jumpmind/pos/util/clientcontext/ClientContext.java
Labels: majorfeature, releasenote

#1103 Fixes For Training Mode
  openpos-devices/src/test/resources/dev/sql/test/0.0.1_post_01_testData.sql
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/QueryTemplates.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/model/AbstractTaggedModel.java
Labels: bug

#1108 Fix Cucumber Test Failures Caused By Training Mode Changes
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
  openpos-util/src/main/java/org/jumpmind/pos/util/clientcontext/ClientContext.java
Labels: bug

#1092 Fixed app-dynamic-form-part throwing Angular error "Expression changed after it was checked"
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dynamic-form-part/dynamic-form-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dynamic-form-part/dynamic-form-part.component.ts
Labels: releasenote

#1112 Appriss Integration
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/form/form.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dynamic-form-part/dynamic-form-part.component.ts
  openpos-util/src/main/java/org/jumpmind/pos/util/DriversLicense.java
Labels: majorfeature, releasenote

#1115 Fixed AudioService throwing NPE because ContentProviderService is not initialized
  openpos-flow/src/main/java/org/jumpmind/pos/core/audio/AudioActionListener.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/audio/AudioUtil.java
Labels: releasenote

#1126 Build Updates For Cash Management Feature
  openpos-client-libs/package.json
Labels: build

#1125 Initial Scandit Capacitor Support
  openpos-client-libs/package-lock.json
  openpos-client-libs/package.json
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/image-scanners/image-scanner.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/image-scanners/image-scanner.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/image-scanners/image-scanners.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/image-scanners/scandit-capacitor/scandit-capacitor.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/image-scanners/scandit-capacitor/scandit-plugin.capacitor.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platforms/cordova.platform.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/startup.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/capacitor-status-bar-platform-plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/final-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/platform-ready-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/plugin-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/subscribe-to-session-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/screens-with-parts.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/scan-or-search/scan-or-search.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/scan-or-search/scan-or-search.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/scan-or-search/scan-or-search.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/shared.module.ts
Labels: releasenote

#1127 Prevent Multiple Clients to Connect to the Same Device Simultaneously
  openpos-server-core/src/main/java/org/jumpmind/pos/server/config/WebSocketConfig.java
  openpos-server-core/src/main/java/org/jumpmind/pos/server/model/SessionContext.java
Labels: releasenote

#1131 Fixed missing image placeholder showing on loyalty button when there's no image to display
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.html
Labels: releasenote

#1133 Fixed missing image placeholder showing on loyalty button when there's no image to display (Master)
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.html
  openpos-util/src/main/java/org/jumpmind/pos/util/DriversLicense.java
Labels: releasenote

#1128 Feature/grid table row line action item
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/grid-table/grid-table.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/grid-table/grid-table.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/grid-table/grid-table.component.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/DataTableRow.java
Labels: releasenote

#1129 Feature/grid table row line action item master
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/grid-table/grid-table.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/grid-table/grid-table.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/grid-table/grid-table.component.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/DataTableRow.java
Labels: releasenote

#1140 Fixed enter key triggering "back" action on Tendering screen
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/choose-options-part/choose-options-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/options-list/options-list.component.html
Labels: releasenote

#1141 Fixed enter key triggering "back" action on Tendering screen (Master)
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/choose-options-part/choose-options-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/options-list/options-list.component.html
Labels: releasenote

#1139 Round up donation at tendering
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/icon.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/tender-part/tender-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/tender-part/tender-part.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/tender-part/tender-part.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/tender-part/tender-part.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/IconType.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/TenderUIMessage.java
  openpos-flow/src/main/resources/content/icons/heart_plus_outline.svg
Labels: releasenote

#1145 Application is crashing because the wrong application.yml is being found
  openpos-flow/src/main/resources/application.yml
Labels: bug, releasenote

#1150 Scanner Platform Refresh
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/aila-scanner-cordova/aila-barcode-type.enum.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/aila-scanner-cordova/aila-scanner-cordova.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/aila-scanner-cordova/aila-to-openpos-barcode-type.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/barcode-scanner.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/console-scanner/console-scanner.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/image-scanner.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/infinea-scanner-cordova/infinea-barcode-type.enum.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/infinea-scanner-cordova/infinea-scanner-cordova.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/infinea-scanner-cordova/infinea-to-openpos-barcode-type.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/scandit-capacitor/scandit-capacitor.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/scandit-capacitor/scandit-plugin.capacitor.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/scandit-scanner-cordova/README.md
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/scandit-scanner-cordova/overlay-view-settings.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/scandit-scanner-cordova/scandit-scanner-cordova.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/scandit-scanner-cordova/scandit-to-openpos-barcode-type.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/scandit-scanner-cordova/types/barcode.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/scanner.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/server-scanner/server-scanner.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/wedge-scanner/README.md
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/wedge-scanner/wedge-scanner-accepted-keys.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/wedge-scanner/wedge-scanner.plugin.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/wedge-scanner/wedge-scanner.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/image-scanners/image-scanner.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/image-scanners/image-scanners.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/image-scanners/scandit-capacitor/scandit-capacitor.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/README.md
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/aila-scanner-cordova/aila-scanner-cordova.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/console-scanner/console-scanner.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/infinea-scanner-cordova/infinea-scanner-cordova.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/infinea-scanner-cordova/infinea-to-openpos-barcode-type.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/openpos-scan-type.enum.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/scan.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/scandit-scanner-cordova/scandit-camera-view/scandit-camera-view.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/scandit-scanner-cordova/scandit-camera-view/scandit-camera-view.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/scandit-scanner-cordova/scandit-camera-view/scandit-camera-view.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/scandit-scanner-cordova/scandit-scanner-cordova.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/scandit-scanner-cordova/scandit-to-openpos-barcode-type.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/scanner.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/scanner.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/server-scanner/server-scanner.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platforms/capacitor-android.platform.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platforms/capacitor-ios.platform.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/configuration.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/plugin-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/sale.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/sale.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/bacon-strip/bacon-strip.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/scan-or-search/scan-or-search.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/scan-or-search/scan-or-search.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/scan-part/scan-part.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/search-expand-input/search-expand-input.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/shared.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/public-api.ts
Labels: bug, majorfeature, releasenote

#1155 Transaction Date/Time on Safari
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.ts
Labels: bug

#1157 Update the device with the timezone from the client to be consistent and for use in updating unit status
  openpos-devices/src/main/java/org/jumpmind/pos/devices/DeviceUpdater.java
Labels: bug, releasenote

#1158 Added an endpoint that finds devices for a business unit
  openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DevicesRepository.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/FindDevicesEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/IDevicesService.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/model/FindDevicesRequest.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/model/FindDevicesResponse.java
  openpos-devices/src/test/java/org/jumpmind/pos/devices/service/AuthenticateDeviceEndpointTest.java
  openpos-devices/src/test/java/org/jumpmind/pos/devices/service/GetDeviceEndpointTest.java
Labels: releasenote
