Repository JumpMind/openpos-framework, pull requests merged in 2021-12, with the labels that each got.

#1776 Removed domain filter with AE specific domain
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/personalization-startup-task.ts
Labels: bug

#1784 Cache i18n requests at the client to reduce network noise
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/locale.service.ts
  openpos-service/src/main/java/org/jumpmind/pos/service/GlobalExceptionHandler.java
Labels: bug, enhancement, releasenote

#1797 Included additional datetime format in ReflectUtils.java
  openpos-util/src/main/java/org/jumpmind/pos/util/ReflectUtils.java
Labels: enhancement

#1805 Remove log4j-core. It is not used.
  openpos-gradle/src/main/resources/openpos.gradle
  openpos-persist/src/main/java/org/jumpmind/symmetric/util/LogSummaryAppenderUtils.java
Labels: bug

#1810 Switched to using IPC for Non-Functional Electron Dev Tools
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dev-menu/dev-menu.component.ts
Labels: bug

#1815 Startup 2.0
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/audio/audio-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/components/openpos-app/openpos-app.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/components/openpos-app/openpos-app.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/components/splash-screen/splash-screen.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/components/splash-screen/splash-screen.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/platform-plugin.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platforms/capacitor-ios.platform.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platforms/platform.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/splash-screen.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/startup.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/startup.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/README.md
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/capacitor-status-bar-platform-plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/final-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/personalization-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/platform-ready-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/plugin-startup-task.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/plugin-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-controller.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-failed.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-failed.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-failed.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-sequence.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-task-data.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-task-names.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-task.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-task.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/subscribe-to-session-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/audio.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/auto-personalization.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/capacitor-hide-statusbar.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/initialize-personalization.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/manual-personalization.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/platform-discovery.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/platform-plugins.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/query-params-personalization.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/saved-session-personalization.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/session-connect.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/zero-conf-personalization.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/zeroconf/capacitor-zeroconf.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/zeroconf/mdns-zeroconf.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/zeroconf/zeroconf.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/openpos-app/openpos-app.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/shared.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/public-api.ts
Labels: enhancement, majorfeature

#1823 Experimental Prompt w/ Multiple Inputs and Working Form Validation
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt2/form.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt2/prompt2-screen-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt2/prompt2-screen-dialog.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt2/prompt2-screen-dialog.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/screens-with-parts.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/validators/custom-date-validators.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UIMessageType.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/prompt/BaseInputPrompt.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/prompt/DateFormat.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/prompt/DatePromptInput.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/prompt/PromptItem.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/prompt/PromptItemTypes.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/prompt/PromptPlusPlusUIMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/prompt/TextPromptInput.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/prompt/TextPromptInputKind.java
Labels: enhancement

#1828 Added NgZone to Capacitor Events
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/image-scanner.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/scandit-capacitor/scandit-capacitor.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/power/capacitor/capacitor-power-supplier.ts
Labels: bug

#1830 Force a change detection after receiving STOMP messages
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/session.service.ts
Labels: bug
