Repository JumpMind/openpos-framework, pull requests merged in 2021-09, with the labels that each got.

#1569 Add asterisk for Date Of Birth field
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-date-form-field/dynamic-date-form-field.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-date-form-field/dynamic-date-form-field.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-form-field/dynamic-form-field.component.html
Labels: bug

#1577 Add Support for Custom Group Display Name when Not a Member
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/_membership-display-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/membership-display.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/membership-display.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/memebership-display.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UIMembership.java
Labels: releasenote

#1580 Customer Membership Dialog Tidy Up Styles
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/_customer-details-dialog-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/membership-display.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-points-display/membership-points-display.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/_core.scss
Labels: bug

#1586 Capacitor 3 Upgrade
  openpos-client-libs/package-lock.json
  openpos-client-libs/package.json
  openpos-client-libs/projects/openpos-client-core-lib/ng-package.json
  openpos-client-libs/projects/openpos-client-core-lib/package.json
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/scandit-capacitor/scandit-capacitor.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/scandit-capacitor/scandit-plugin.capacitor.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/kiosk/capacitor-kiosk/capacitor-kiosk-platform.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/power/capacitor/capacitor-power-supplier.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/printers/capacitor-printer.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platforms/config-provider/capacitor/capacitor-platform-config.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platforms/config-provider/capacitor/capacitor-plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/capacitor.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/capacitor-status-bar-platform-plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/storage/capacitor/capacitor-storage.service.ts
Labels: releasenote, majorfeature

#1587 Purchase History Filter Causes Browser Crash
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/icon/icon.component.ts
Labels: bug

#1592 Membership Details - Add Filter Button
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/_customer-details-dialog-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/CustomerDetailsUIMessage.java
Labels: bug

#1635 Disabled auto everything for iOS/android keyboards.
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/disable-auto-complete.directive.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/shared.module.ts
Labels: bug
