Repository JumpMind/openpos-framework, pull requests merged in 2021-03, with the labels that each got.

#1162 Remove unneeded auto wiring of services on every call
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInjector.java
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
  openpos-service/src/main/java/org/jumpmind/pos/service/IServiceContextProvider.java
  openpos-service/src/main/java/org/jumpmind/pos/service/In.java
  openpos-service/src/main/java/org/jumpmind/pos/service/InjectionContext.java
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/AbstractInvocationStrategy.java
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/LocalOnlyStrategy.java
Labels: performance, releasenote

#1173 Capacitor Printer
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/print-message.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/printers/browser-printer.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/printers/capacitor-printer.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/printers/printer.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/printers/printer.service.ts
  openpos-util/src/main/java/org/jumpmind/pos/util/model/PrintMessage.java
Labels: releasenote

#1177 Image Scanner Support on Prompts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/image-scanner.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part/prompt-form-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part/prompt-form-part.interface.ts
Labels: releasenote

#1186 Fixed the lock screen area to help iOS input.
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/lock-screen/lock-screen.component.scss
Labels: bug

#1190 Feature/membership
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/_screen-with-parts-themes.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/_customer-details-dialog-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/screens-with-parts.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/_screen-part-themes.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/_customer-information-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/_membership-display-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/membership-display.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/membership-display.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/membership-display.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/membership-display.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/memebership-display.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-history-line-item/_rewards-history-line-item-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-history-line-item/rewards-history-line-item.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-history-line-item/rewards-history-line-item.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-history-line-item/rewards-history-line-item.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-history-line-item/rewards-history-line-item.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-history-line-item/rewards-history-line-item.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/_rewards-line-item-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/shared.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/mixins/_icon.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/utilites/test-utils.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/CustomerDetailsUIMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/SaleUIMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UIAddress.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UICustomerDetails.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UILoyaltyReward.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UIMembership.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UIMessageType.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UIRewardHistory.java
  openpos-flow/src/main/resources/content/icons/account_heart.svg
  openpos-flow/src/main/resources/content/icons/card_account_details.svg
Labels: releasenote

#1191 WebKit Item Image
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/item-card/item-card.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/item-card/item-card.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/mobile-item/mobile-item.component.scss
Labels: bug

#1204 [ISR] Updated the currency text to support ranges of numbers.
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/currency-text/currency-text.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/currency-text/currency-text.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/currency-text/currency-text.component.ts
Labels: enhancement
