Repository JumpMind/openpos-framework, pull requests merged in 2021-04, with the labels that each got.

#1226 Product Option Selection
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/_screen-with-parts-themes.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/buddy-store.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/basic-product-option-part/_basic-product-option-part-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/basic-product-option-part/basic-product-option-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/basic-product-option-part/basic-product-option-part.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/basic-product-option-part/basic-product-option-part.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/basic-product-option-part/basic-product-option-part.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/swatch-product-option-part/_swatch-product-option-part-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/swatch-product-option-part/swatch-product-option-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/swatch-product-option-part/swatch-product-option-part.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/swatch-product-option-part/swatch-product-option-part.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/swatch-product-option-part/swatch-product-option-part.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/swatch-product-option-part/swatch.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/product-option.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/screens-with-parts.module.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/BuddyStore.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/ItemDetailUIMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/ProductOptionComponent.java
Labels: parameterchange

#1231 Allow injectable datasources to be overridden by module
  openpos-service/src/main/java/org/jumpmind/pos/service/AbstractRDBMSModule.java
Labels: releasenote

#1238 Feature/isr detail UI
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/actions/action-item.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/basic-product-option-part/basic-product-option-part.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/swatch-product-option-part/swatch-product-option-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/swatch-product-option-part/swatch-product-option-part.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/display-property/display-property-alignment.enum.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/display-property/display-property.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/_app-theme.scss
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/ActionItem.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/ItemDetailUIMessage.java
Labels: database change

#1244 Better logging for jackson serialization failures. Exception gets swallowed.
  openpos-util/src/main/java/org/jumpmind/pos/util/web/ConfiguredRestTemplate.java
Labels: bug, releasenote

#1247 Support mutable longs in the persistence layer
  openpos-util/src/main/java/org/jumpmind/pos/util/ReflectUtils.java
Labels: bug, releasenote

#1252 Migrate Caching of Method Invocations From Master
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/LocalOnlyStrategy.java
Labels: bug, performance

#1254 Cherry Pick Training Mode Changes From 1.9/1.10 To Master
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/message-types.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/watermark-message.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-screen/dynamic-screen.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-screen/dynamic-screen.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/watermark/watermark.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/watermark/watermark.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/watermark/watermark.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/shared.module.ts
  openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DeviceModel.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/ApplicationState.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/IStateManager.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/StateManager.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/model/MessageType.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/HideWatermark.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/Watermark.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSessionFactory.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/AbstractSqlTemplates.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/DatabaseSchema.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/DmlTemplate.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/DmlTemplates.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelClassMetaData.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelWrapper.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/QueryTemplate.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/QueryTemplates.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ShadowTablesConfigModel.java
  openpos-persist/src/test/java/org/jumpmind/pos/persist/DBSessionQueryConcurrentTest.java
  openpos-persist/src/test/java/org/jumpmind/pos/persist/cars/DelegateTestContextConfig.java
  openpos-persist/src/test/java/org/jumpmind/pos/persist/cars/TestPersistCarsConfig.java
  openpos-persist/src/test/resources/persist-test-query.yml
  openpos-service/src/main/java/org/jumpmind/pos/service/AbstractRDBMSModule.java
  openpos-service/src/main/java/org/jumpmind/pos/service/Endpoint.java
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/LocalOnlyStrategy.java
  openpos-test/src/main/java/org/jumpmind/pos/test/ClientContextTestUtils.java
  openpos-util/src/main/java/org/jumpmind/pos/util/clientcontext/ClientContext.java
Labels: architecture, majorfeature, releasenote

#1261 Adding support for displaying card numbers for partial tender list
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/tender-part/tender-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/tender-part/tender-part.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/tender-part/tender.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/model/Tender.java
Labels: releasenote

#1258 Update SymmetricDS version to 3.12.8
  openpos-assemble/gradle.properties
  openpos-persist/src/main/java/org/jumpmind/db/platform/AbstractJdbcDdlReader.java
  openpos-persist/src/main/java/org/jumpmind/symmetric/util/LogSummaryAppenderUtils.java
  openpos-persist/src/test/java/org/jumpmind/pos/persist/cars/PersistTestUtil.java
  openpos-service/src/main/java/org/jumpmind/pos/service/AbstractRDBMSModule.java
Labels: releasenote

#1289 Added a check for `undefined` options
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.ts
Labels: bug

#1292 Fixed theme not being applied to dynamic screen host
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-screen/dynamic-screen.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-screen/dynamic-screen.component.ts
Labels: bug

#1297 Fixed wedge scanner not working after first try
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/wedge-scanner/wedge-scanner.plugin.ts
Labels: bug

#1301 Show Tenders on Returns
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/interfaces/tender-item.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/selection-list/selection-list-item-display-property.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/selection-list/selection-list-screen-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/selection-list/selection-list-screen.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/_component-theme-mixins.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/receipt-card/_receipt-card-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/receipt-card/receipt-card.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/receipt-card/receipt-card.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/receipt-card/transaction-receipt.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/SelectionListItem.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/SelectionListItemDisplayProperty.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/TenderItem.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/TextAlignment.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/TransactionReceipt.java
Labels: majorfeature, releasenote

#1310 Sale Promo Details
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/interfaces/sell-item.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/item-card/item-card.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/item-card/item-card.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/mobile-item/mobile-item.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/mobile-item/mobile-item.component.scss
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/AdditionalLabel.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/SellItem.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/messagepart/DialogHeaderPart.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/messagepart/PromptButtonRowPart.java
Labels: enhancement, releasenote
