Repository JumpMind/openpos-framework, pull requests merged in 2021-06, with the labels that each got.

#1381 fixed bad merge with personalization
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/wrapper.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/auto-personalization-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/personalization-startup-task.ts
Labels: bug

#1380 Enforce the use of API tokens for REST API endpoints
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/AuthenticateDeviceEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetDeviceEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetDevicePersonalizationModelEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetMyDeviceEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetPersonalizationConfigEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/IDevicesService.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/PersonalizeEndpoint.java
  openpos-server-core/src/main/java/org/jumpmind/pos/server/config/SwaggerConfig.java
  openpos-service/src/test/java/org/jumpmind/pos/service/utils/AbstractServiceMockRequestBuilder.java
  openpos-util/src/main/java/org/jumpmind/pos/util/ApiTokenGenerator.java
  openpos-util/src/main/java/org/jumpmind/pos/util/RestApiSupport.java
  openpos-util/src/test/java/org/jumpmind/pos/util/ApiTokenGeneratorTest.java
Labels: majorfeature, parameterchange, releasenote

#1393 Connecting to Server... dialog only closed after screen message comes through
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/session.service.ts
Labels: bug

#1409 Event broadcasting to paired device also goes to self
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/EventBroadcaster.java
  openpos-flow/src/test/java/org/jumpmind/pos/core/flow/EventBroadcasterTest.java
  openpos-util/src/main/java/org/jumpmind/pos/util/event/AppEvent.java
Labels: releasenote

#1272 Fix So Shadow Tables Are Created With Tagged/Augmented Columns
  openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSessionFactory.java
Labels: bug

#1413 Add Rewards Item History
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/_customer-details-dialog-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/TransactionIdentifier.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/data/TransactionSummary.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/CustomerDetailsUIMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UILabel.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UIPurchasedItem.java
Labels: enhancement, releasenote

#1425 Multiple `@Endpoint` Handler Support
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
  openpos-service/src/main/java/org/jumpmind/pos/service/Endpoints.java
Labels: enhancement

#1435 Feature/customer display loyalty signup
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/loyalty-signup-message.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/message-types.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/customer-search-result-dialog/customer-search-result-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/customer-search-result-dialog/customer-search-result-dialog.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/dynamic-form-dialog/dynamic-form.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/dynamic-form-dialog/dynamic-form.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/animations/_animations.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/providers/keypress.provider.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dynamic-form-part/dynamic-form-part.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/_app-theme.scss
  openpos-flow/src/main/java/org/jumpmind/pos/core/error/DefaultErrorHandler.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/EventBroadcaster.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/config/YamlFlowConfigFileLoader.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/config/YamlStateConfig.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/model/MessageType.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/service/DevToolsActionListener.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/LoyaltySignupMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/ReturnUIMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/SaleUIMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UIMessageType.java
  openpos-flow/src/test/java/org/jumpmind/pos/core/flow/EventBroadcasterTest.java
  openpos-util/src/main/java/org/jumpmind/pos/util/ReflectUtils.java
  openpos-util/src/main/java/org/jumpmind/pos/util/event/AppEvent.java
  openpos-util/src/main/java/org/jumpmind/pos/util/event/DevicePairedEvent.java
  openpos-util/src/main/java/org/jumpmind/pos/util/event/ErrorEvent.java
Labels: majorfeature, releasenote
