Repository JumpMind/openpos-framework, pull requests merged in 2021-07, with the labels that each got.

#1429 Made it so the AutoFocus ability of prompts is configured through the prompt message.
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part/prompt-form-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part/prompt-form-part.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/prompt-form-part/prompt-form-part.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/PromptUIMessage.java
Labels: enhancement

#1427 Customer Item History Filtering
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/_customer-details-dialog-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/CustomerDetailsUIMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UICustomerItemHistoryFilter.java
Labels: enhancement

#1445 Added Dev Menu Option to Skip Auto Personalization
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/personalization-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/storage/storage.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dev-menu/dev-menu.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dev-menu/dev-menu.component.ts
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/model/ParseDevicePersonalizationConfig.java
Labels: enhancement

#1437 Remove duplicate search component on mobile screens
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/return/return.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/sale.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/bacon-strip/bacon-strip.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/bacon-strip/bacon-strip.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/search-expand-input/search-expand-input.component.ts
Labels: bug

#1456 Fixed personalization getting stuck when skipping.
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/personalization-startup-task.ts
Labels: bug

#1458 Fixed bug regarding Image Scanner's not resizing when their container changes size.
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/debug-image-scanner/debug-image-scanner.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/image-scanner.component.ts
Labels: bug

#1454 Cherry-pick peripheral selection `isEnabled` addition from `releases/2.2`
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/peripheral-device-selection.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/peripherals/peripheral-selection.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/item/status-details-item.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/item/status-details-item.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/status-details.component.html
  openpos-util/src/main/java/org/jumpmind/pos/util/peripheral/IPeripheralDeviceSelector.java
  openpos-util/src/main/java/org/jumpmind/pos/util/peripheral/PeripheralDeviceSelectionMessage.java
Labels: bug

#1459 Item Details Fixes
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/option-components/swatch-product-option-part/swatch-product-option-part.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/carousel/carousel.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/carousel/carousel.component.scss
Labels: bug

#1455 Show Cashier What's Up on Customer Display
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/loyalty-signup-message.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/loyalty-signup.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/animations/_animations.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/animations/glow.animation.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/animations/gradient-inner-glow.animation.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/animations/shake.animation.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/animations/swing.animation.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/animations/throb.animation.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/shared.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/_app-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/public-api.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/LoyaltySignupMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/ReturnUIMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/SaleUIMessage.java
Labels: majorfeature, releasenote

#1479 Order Review Redesign mOrE bEtTeR
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/interfaces/address.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/_customer-details-dialog-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.ts
Labels: releasenote

#1499 Right-Align Item Availability Inventory Count
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.scss
Labels: bug

#1502 Avoid infinite recursion StackOverflowError in ObjectFinder
  .gitignore
  openpos-util/src/main/java/org/jumpmind/pos/util/ObjectFinder.java
Labels: bug
