Repository JumpMind/openpos-framework, pull requests merged in 2021-01, with the labels that each got.

#1049 Upgrade SymmetricDS to 3.12.5
  openpos-assemble/gradle.properties
  openpos-flow/src/main/java/org/jumpmind/pos/core/audio/AudioService.java
  openpos-persist/build.gradle
  openpos-persist/src/main/java/org/jumpmind/db/platform/AbstractJdbcDdlReader.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSessionFactory.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/driver/StatementBypassInterceptor.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/DatabaseSchema.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/ModelClassMetaData.java
  openpos-service/src/main/java/org/jumpmind/pos/service/AbstractRDBMSModule.java
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
  openpos-service/src/main/java/org/jumpmind/pos/service/ModuleEnabledCondition.java
  openpos-service/src/main/java/org/jumpmind/pos/service/startup/ModuleRegistry.java
Labels: releasenote

#1060 Fixed forms submitting when they're invalid
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/form/form.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dynamic-form-part/dynamic-form-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dynamic-form-part/dynamic-form-part.component.ts
Labels: releasenote

#1062 Allow java.util.Date and other java objects to be queries from the persistence layer
  .gitignore
  openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
Labels: bug, releasenote

#1063 Fixed scanning customer id not correctly parsing a valid driver's license for Appriss
  openpos-util/src/main/java/org/jumpmind/pos/util/DriversLicense.java
Labels: releasenote

#1061 Disable Printer Status on Mobile Printing
  openpos-peripheral/src/main/java/org/jumpmind/pos/peripheral/poledisplay/PoleDisplay.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/print/EscpPOSPrinter.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/print/IOpenposPrinter.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/print/IPrinterStatusReporter.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/print/LogPOSPrinter.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/print/NoopPrinterStatusReporter.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/print/StatusManagerPrinterStatusReporter.java
Labels: releasenote

#1066 Oracle creates an array of the size of the fetchSize. It needs to be a reasonable number.
  openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
Labels: bug, releasenote

#1073 Remove deviceType from DeviceModel
  openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DeviceModel.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/PersonalizeEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/model/PersonalizationRequest.java
  openpos-devices/src/test/java/org/jumpmind/pos/devices/model/DevicesRepositoryTest.java
  openpos-devices/src/test/java/org/jumpmind/pos/devices/service/PersonalizationEndpointTest.java
  openpos-devices/src/test/resources/dev/sql/test/0.0.1_post_01_testData.sql
Labels: releasenote

#1072 Require that flow extensions have the suffix of *-flow-ext.yml
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/FlowException.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/config/YamlConfigProvider.java
  openpos-flow/src/test/java/org/jumpmind/pos/core/flow/StateManagerTestUtils.java
  openpos-flow/src/test/resources/testflows/test-extended-flow-ext.yml
Labels: bug, releasenote

#1076 The device model drives queries to other tables. It should not include tag_ columns that are not defined in the yml config
  openpos-persist/src/main/java/org/jumpmind/pos/persist/model/TagConfig.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/model/TagHelper.java
Labels: bug, releasenote

#1080 Fix error in the log file during session disconnect
  openpos-flow/src/main/java/org/jumpmind/pos/core/service/SessionDisconnectedListener.java
Labels: bug

#1081 Initial Implementation of Status Bar Details
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/message-types.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/peripheral-device-selection.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/peripherals/peripheral-selection.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/locale.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/status/status-bar/status-bar.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/status/status.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-screen/dynamic-screen.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-screen/dynamic-screen.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/modal-overlay-container/modal-overlay-container.directive.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/modal-overlay-container/modal-overlay-container.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/pipes/localize.pipe.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/shared.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/_status-bar-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/item/status-details-item.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/item/status-details-item.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/item/status-details-item.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/selector/peripheral-selector.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/selector/peripheral-selector.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/selector/peripheral-selector.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/status-details.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/status-details.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/status-details.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status.message.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/_app-theme.scss
  openpos-util/src/main/java/org/jumpmind/pos/util/peripheral/CategoryDescriptor.java
  openpos-util/src/main/java/org/jumpmind/pos/util/peripheral/IInvalidationHandle.java
  openpos-util/src/main/java/org/jumpmind/pos/util/peripheral/IPeripheralDeviceSelector.java
  openpos-util/src/main/java/org/jumpmind/pos/util/peripheral/PeripheralDeviceDescription.java
  openpos-util/src/main/java/org/jumpmind/pos/util/peripheral/PeripheralDeviceSelectionMessage.java
Labels: majorfeature, releasenote

#1091 Fixed app-dynamic-form-part throwing Angular error "Expression changed after it was checked"
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dynamic-form-part/dynamic-form-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dynamic-form-part/dynamic-form-part.component.ts
Labels: releasenote

#1087 Feature/support checkout scale
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/message-types.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/screen-value-update-message.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/prompt-input/prompt-input.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/screen-part.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/IconType.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/ScreenValueUpdateMessage.java
  openpos-flow/src/main/resources/content/icons/checkout_scale.svg
  openpos-peripheral/src/main/java/org/jumpmind/pos/peripheral/IPlugAndPlayDevice.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/peripheral/PeripheralException.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/peripheral/poledisplay/PoleDisplay.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/peripheral/scale/CheckoutScale.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/peripheral/scale/DetectoAPS10CheckoutScale.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/peripheral/scale/DetectoCheckoutScale.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/peripheral/scale/ICheckoutScale.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/peripheral/scale/MettlerCheckoutScale.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/peripheral/scale/ScaleWeightData.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/print/LogPOSPrinter.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/print/RS232ConnectionFactory.java
  openpos-peripheral/src/main/java/org/jumpmind/pos/print/UsbConnectionFactory.java
  openpos-peripheral/src/test/java/org/jumpmind/pos/print/CheckoutScaleTester.java
Labels: majorfeature, releasenote

#1089 Feature/client executable action
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/actions/action-item.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/actions/action.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/interfaces/client-execute-config.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/messages/message-types.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/client-executable.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/toast.service.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/model/MessageType.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/ActionItem.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/ClientExecutableConfigMessage.java
  openpos-util/src/main/java/org/jumpmind/pos/util/model/Message.java
Labels: releasenote
