Repository JumpMind/openpos-framework, pull requests merged in 2021-05, with the labels that each got.

#1314 Fixed bug with price ranges displaying even when prices are the same
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/currency-text/currency-text.component.ts
Labels: bug

#1273 Cherry Pick Training Mode Bug Fixes From Master
  openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSessionFactory.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/impl/DatabaseSchema.java
  openpos-service/src/main/java/org/jumpmind/pos/service/AbstractRDBMSModule.java
Labels: bug

#1316 Bugfix/timeout cherry pick
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/IStateManager.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/StateManager.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/config/ScreenConfig.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/config/ScreensConfig.java
  openpos-server-core/src/main/java/org/jumpmind/pos/server/model/Action.java
Labels: enhancement, parameterchange

#1315 Client Auto configuration
  openpos-client-libs/package-lock.json
  openpos-client-libs/package.json
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/configuration/configuration.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/device-personalization.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/printers/dpp-255-capacitor.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/scanners/infinea-scanner/infinea-scanner-capacitor/infinea-scanner-capacitor.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/capacitor.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/wrapper.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/auto-personalization-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/personalization-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-task-names.ts
  openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DevicePersonalizationModel.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DevicesRepository.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetDevicePersonalizationModelEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/model/ParseDevicePersonalizationConfig.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/model/PersonalizeMeResponse.java
Labels: database change

#1340 Fixed Sale Screen Not Showing Return Items (Master)
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-item-card-list/sale-item-card-list.component.html
Labels: releasenote

#1342 Added SYM config support for new CTX_CODE table, overloaded addComboBox in Form.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/model/Form.java
  openpos-symds/src/test/resources/sym/sql/demo/0.0.1_post_02_demo-symds-config.sql
Labels: database change, majorfeature, releasenote

#1333 Small Item Search Bug Fixes
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/item-detail/item-detail.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/ItemDetailUIMessage.java
  openpos-flow/src/main/resources/content/icons/inventory_2.svg
Labels: bug

#1357 Added SYM config support for new CTX_CODE table, Customer add/edit bugfix
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/loyalty-customer-form-dialog/loyalty-customer-form-dialog.component.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/model/Form.java
  openpos-symds/src/test/resources/sym/sql/demo/0.0.1_post_02_demo-symds-config.sql
Labels: database change, majorfeature, releasenote

#1363 Fixed Register Electron support for Auto Personalization
  openpos-client-libs/package-lock.json
  openpos-client-libs/package.json
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/configuration/configuration.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/device-personalization.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/scandit-capacitor/scandit-capacitor.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/capacitor.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/personalization-startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-task-names.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/zeroconf/capacitor-zeroconf.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/zeroconf/mdns-zeroconf.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/zeroconf/zeroconf.ts
  openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DevicePersonalizationModel.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DevicesRepository.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetDevicePersonalizationModelEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/model/ParseDevicePersonalizationConfig.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/model/PersonalizeMeResponse.java
Labels: enhancement

#1374 One Document at a Time Printing
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/printers/browser-printer.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/printers/capacitor-printer.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/printers/printer.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/printers/printer.service.ts
Labels: bug, releasenote

#1376 Fixed bug where closing status details would close screen dialogs too.
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-details/status-details.component.ts
Labels: bug
