Repository JumpMind/openpos-framework, pull requests merged in 2021-11, with the labels that each got.

#1712 Removed Domain Filter from mDNS requests
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/personalization-startup-task.ts
Labels: bug

#1715 Customer Picks Suggested or Corrected Address
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dialog-header/dialog-header.component.scss
Labels: majorfeature

#1696 Lazy query iterations
  openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/Query.java
  openpos-persist/src/main/java/org/jumpmind/pos/persist/RowConsumerContext.java
Labels: majorfeature

#1730 Fixed bugs in auto personalization.
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/personalization-startup-task.ts
Labels: bug

#1739 Validate Greg on First Load
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/interfaces/form.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/form-builder.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/loyalty-customer-form-dialog/loyalty-customer-form-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/form/form.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/auto-complete-address-part/auto-complete-address-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/choose-options-part/choose-options-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dynamic-form-part/dynamic-form-part.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dynamic-form-part/dynamic-form-part.component.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/model/Form.java
Labels: bug

#1711 Updates to enhance support for one server and multiple clients having different business unit IDs - master
  openpos-devices/src/main/java/org/jumpmind/pos/devices/DeviceUpdater.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DevicePersonalizationModel.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetDevicePersonalizationModelEndpoint.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/strategy/GetBusinessUnitIdFromConfigStrategy.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/strategy/GetBusinessUnitIdFromPersonalizationParamsStrategy.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/strategy/IDeviceBusinessUnitIdStrategy.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/strategy/ParseBusinessUnitIdFromDeviceIdStrategy.java
  openpos-devices/src/test/java/org/jumpmind/pos/devices/service/strategy/GetBusinessUnitIdFromConfigStrategyTest.java
  openpos-devices/src/test/java/org/jumpmind/pos/devices/service/strategy/GetBusinessUnitIdFromPersonalizationParamsStrategyTest.java
  openpos-devices/src/test/java/org/jumpmind/pos/devices/service/strategy/ParseBusinessUnitIdFromDeviceIdStrategyTest.java
  openpos-devices/src/test/resources/application-test.yml
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/IStateManager.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/LocationChangedGlobalActionHandler.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/StateManager.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/flow/StateManagerContainer.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/service/SessionSubscribedListener.java
  openpos-server-core/src/main/java/org/jumpmind/pos/server/service/SessionConnectListener.java
  openpos-server-core/src/test/java/org/jumpmind/pos/server/service/SessionConnectListenerTest.java
  openpos-service/src/main/java/org/jumpmind/pos/service/AbstractRDBMSModule.java
  openpos-util/src/main/java/org/jumpmind/pos/util/JSONUtils.java
  openpos-util/src/main/java/org/jumpmind/pos/util/clientcontext/ClientContext.java
Labels: releasenote, parameterchange, database change

#1752 Fix Checkout Button Pushed Off Screen
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/sale.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/sale.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/primary-button/primary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/secondary-button/secondary-button.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/membership-display.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-points-display/membership-points-display.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.scss
Labels: bug

#1756 Don't Squash the Form!
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/dynamic-form-dialog/dynamic-form.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/dynamic-form-dialog/dynamic-form.component.scss
Labels: bug

#1767 To add plcc look up button/account details on customer details screen in Real rewards flow /plcc look up flow
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/customer-details-dialog/customer-details-dialog.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.interface.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/CustomerDetailsUIMessage.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/UICustomerDetailsItem.java
Labels: majorfeature
