Repository JumpMind/openpos-framework, pull requests merged in 2022-03, with the labels that each got.

#2075 Fix Redundant Display Of Loyalty/Membership Info On Mobile
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/mobile-loyalty-part/mobile-loyalty-part.component.html
Labels: bug, client

#2086 Fixed unusable modal dialogs for mobile & other minor UI bugs
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/customer-display/customer-display-return/customer-display-return.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/customer-display/customer-display-sale/customer-display-sale.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/customer-details-dialog/_customer-details-dialog-theme.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/customer-details-dialog/customer-details-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/customer-details-dialog/customer-details-dialog.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/home/home.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/layout-components/waffle/waffle.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dual-action-dialog-header/dual-action-dialog-header.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/status/status-bar/status-bar.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/styles/_app-theme.scss
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/messagepart/MessagePartConstants.java
Labels: client

#2096 On Supported Platforms, Always Try to Auto-Personalize
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/startup-sequence.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/auto-personalization.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/zero-conf-personalization.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/zeroconf/zero-conf-personalization-dialog.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/zeroconf/zero-conf-personalization-dialog.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/zeroconf/zero-conf-personalization-dialog.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/zeroconf/zero-conf-personalization.startup-task.ts
Labels: enhancement

#2120 Keybindings Need to be More Defensive
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/providers/keypress.provider.ts
Labels: release bug

#2135 Loyalty Signup Button not Updating from Customer Display
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/LoyaltySignupMessage.java
Labels: milestone bug

#2137 Membership - Non-Member Shows Blank Name
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/membership-display.component.html
Labels: milestone bug
