Repository JumpMind/openpos-framework, pull requests merged in 2022-04, with the labels that each got.

#2146 Add Reset Device Button to Dev Tools In Place of Restart Node
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dev-menu/dev-menu.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dev-menu/dev-menu.component.ts
  openpos-flow/src/main/java/org/jumpmind/pos/core/service/DevToolsActionListener.java
Labels: enhancement, client

#2152 Improve Query Creation
  openpos-persist/src/main/java/org/jumpmind/pos/persist/Query.java
Labels: enhancement, techdebt

#2170 Stripped out all references to electron to support later versions
  openpos-client-libs/package-lock.json
  openpos-client-libs/package.json
  openpos-client-libs/projects/openpos-client-core-lib/ng-package.json
  openpos-client-libs/projects/openpos-client-core-lib/package.json
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/wedge-scanner/wedge-scanner.plugin.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platforms/electron.platform.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platforms/electron.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/client-executable.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/services/configuration.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/zeroconf/mdns-zeroconf.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/customer-details-dialog/customer-details-dialog.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/customer-search-result-dialog/customer-search-result-dialog.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/loyalty-customer-form-dialog/loyalty-customer-form-dialog.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/sale/sale.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/selection-list/selection-list-screen.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dev-menu/dev-menu.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/transaction-summary/transaction-summary.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/customer-information/customer-information.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/display-customer-lookup/display-customer-lookup.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-display/membership-display.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/membership-points-display/membership-points-display.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-history-line-item/rewards-history-line-item.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/rewards-line-item/rewards-line-item.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-total-panel/sale-total-panel.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/screen-gesture/screen-gesture.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/public-api.ts
Labels: enhancement, techdebt

#2207 Remove Customer Display State Manager on Disconnect
  openpos-flow/src/main/java/org/jumpmind/pos/core/service/SessionDisconnectedListener.java
Labels: release bug
