Repository JumpMind/openpos-framework, pull requests merged in 2022-05, with the labels that each got.

#2226 Updater Changes
  openpos-update/src/main/java/org/jumpmind/pos/update/service/DownloadEndpoint.java
  openpos-update/src/main/java/org/jumpmind/pos/update/service/ManifestEndpoint.java
  openpos-wrapper/src/main/java/org/jumpmind/pos/wrapper/WindowsService.java
  openpos-wrapper/src/main/java/org/jumpmind/pos/wrapper/WrapperService.java
Labels: bug

#2233 Increased dynamic form mat hints, updated dynamic forms to respect button enabled/disabled property
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-form-field/dynamic-form-field.component.scss
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/dynamic-form-part/dynamic-form-part.component.html
Labels: client

#2250 Fixed 4.0 auto personalization
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/auto-personalization.startup-task.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/zero-conf-personalization.startup-task.ts
Labels: release bug
