Repository JumpMind/openpos-framework, pull requests merged in 2022-01, with the labels that each got.

#1834 Fixed date validation when using the date picker.
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt2/prompt2-screen-dialog.component.ts
Labels: bug

#1844 Use types from the DML statement. The DML statement could be a merge
  openpos-persist/src/main/java/org/jumpmind/pos/persist/DBSession.java
Labels: production bug

#1864 Fix typo in platform-plugins.startup-task.ts causing scanners to be removed from the SCANNERS array
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/platform-plugins/barcode-scanners/console-scanner/console-scanner.plugin.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/platform-plugins.startup-task.ts
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetDevicePersonalizationModelEndpoint.java
Labels: bug

#1858 PCOM-6298 Add validation to make shopping pass text field readonly
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt2/form.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt2/prompt2-screen-dialog.component.html
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/prompt/TextPromptInput.java
Labels: enhancement

#1857 Fixed Transaction Search Button Sizes
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/transaction-search/transaction-search.component.scss
Labels: client

#1871 Prometheus Metrics for Openpos Internals
  openpos-assemble/gradle.properties
  openpos-flow/build.gradle
  openpos-flow/src/main/java/org/jumpmind/pos/core/service/SessionDisconnectedListener.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/service/SessionSubscribedListener.java
  openpos-flow/src/main/java/org/jumpmind/pos/core/service/SubscribedSessionMetric.java
  openpos-service/build.gradle
  openpos-service/src/main/java/org/jumpmind/pos/service/EndpointInvoker.java
  openpos-service/src/test/java/org/jumpmind/pos/service/EndpointInvokerTest.java
Labels: enhancement

#1883 Retry Auto Personalization More Than Once
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
Labels: production bug

#1888 Cherry-pick: Removed double splicing of plugins. (#1876)
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/tasks/platform-plugins.startup-task.ts
Labels: release bug

#1894 Changed the color of the scan button to primary while active.
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt2/prompt2-screen-dialog.component.html
Labels: release bug

#1897 Add Logging to ErrorDialogMessage Constructors
  openpos-flow/src/main/java/org/jumpmind/pos/core/ui/message/ErrorDialogUIMessage.java
Labels: bug

#1882 Allow submit on scan for image scanners.
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/prompt2/prompt2-screen-dialog.component.ts
Labels: release bug

#1831 New Keybindings Refactor
  openpos-client-libs/gruntfile.js
  openpos-client-libs/projects/openpos-client-core-lib/karma.conf.dev.js
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/components/dialog-content/dialog-content.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/components/dialog-content/dialog-content.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-action-cache.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-action.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-event.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-key.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-lock-screen.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-lock-screen.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-parser.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-property-crawler.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-test.utils.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-zone-screen.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-zone-screen.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-zone.interface.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-zone.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-zone.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-screen/dynamic-screen.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/dynamic-screen/dynamic-screen.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/item-card/item-card.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/item-card/item-card.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/kebab-button/kebab-button.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/kebab-menu/kebab-menu.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/kebab-menu/kebab-menu.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/components/selectable-item-list/selectable-item-list.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/arrow-tab.directive.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/arrow-tab.directive.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/keypress-source.directive.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/providers/disabled-keypress.provider.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/providers/disabled-keypress.provider.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/providers/keypress.provider.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/bacon-strip/bacon-drawer/bacon-drawer.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/bacon-strip/bacon-strip.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/bacon-strip/bacon-strip.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-item-card-list/sale-item-card-list.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-item-card-list/sale-item-card-list.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/public-api.ts
Labels: majorfeature

#1916 Document gets reloaded once on failed personalization request
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
Labels: release bug

#1918 Adjusted home screen buttons grid spacing
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/screens-with-parts/home/home.component.scss
Labels: client

#1922 Allow Dev Menu to show up during initialization or erred states
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/components/openpos-app/openpos-app.component.html
Labels: release bug

#1930 Revert auto-personalization hack in favor of much longer attempt
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/configuration/configuration.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/personalization/personalization.service.ts
Labels: production bug

#1932 New config for auto-focus first options list option
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/configuration/configuration.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/options-list/options-list.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/options-list/options-list.component.ts
Labels: client

#1948 Keybinding Dialog Behavior - Close on Escape by Default
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/core.module.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-dialog.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-dialog.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-test.utils.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/public-api.ts
Labels: bug

#1955 Reduce Keybinding Logging BIG BOY MASSIVE OBJECTS
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-dialog.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-dialog.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-lock-screen.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-lock-screen.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-zone-screen.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-zone-screen.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-zone.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-zone.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/action-item-key-mapping.directive.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/action-item-key-mapping.directive.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/arrow-tab.directive.spec.ts
Labels: bug
