Repository JumpMind/openpos-framework, pull requests merged in 2022-02, with the labels that each got.

#1960 Attempt to personalize with the domain.
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/startup/personalization-startup-task.ts
Labels: production bug

#1964 `getPersonalizationConfig()` should always return available devices
  openpos-devices/src/main/java/org/jumpmind/pos/devices/model/DevicesRepository.java
  openpos-devices/src/main/java/org/jumpmind/pos/devices/service/GetPersonalizationConfigEndpoint.java
Labels: production bug

#1985 Prevent KeybindingDialog service from unintentionally closing "Non-Closeable" dialogs
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-dialog.service.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-dialog.service.ts
Labels: bug

#1999 Limit log message length before sending to NewRelic
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/logging/new-relic/new-relic-sink.service.ts
Labels: release bug

#1997 Add RemoteProfileStatusMonitor for better detection of remote server Offline status
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/RemoteOnlyStrategy.java
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/RemoteProfileOfflineException.java
  openpos-service/src/main/java/org/jumpmind/pos/service/strategy/RemoteProfileStatusMonitor.java
  openpos-service/src/test/java/org/jumpmind/pos/service/RemoteOnlyStrategyTest.java
Labels: parameterchange

#2022 ScanOrSearch Blocks Keybindings When Focused
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/core/keybindings/keybinding-zone.service.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/action-item-key-mapping.directive.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/directives/action-item-key-mapping.directive.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-item-card-list/sale-item-card-list.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/sale-item-card-list/sale-item-card-list.component.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/scan-or-search/scan-or-search.component.html
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/scan-or-search/scan-or-search.component.spec.ts
  openpos-client-libs/projects/openpos-client-core-lib/src/lib/shared/screen-parts/scan-or-search/scan-or-search.component.ts
Labels: bug
